image:
  file: .gitpod.Dockerfile

tasks:
  - init: sdk use java 16.0.1.hs-adpt
    prebuild: cd sportstable; mvn compile
    command: cd sportstable

ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080

