@startuml
title Sequence Diagram
autonumber
Actor you

box UI
you -> GUI: "Writes data"
GUI -> EditTableController : handleSave() *button pushed*
activate EditTableController


EditTableController -> EditTableController : saveTable()
activate EditTableController

EditTableController -> RemoteAppController : setTable(table)
activate EditTableController
activate RemoteAppController
end box

box Core
RemoteAppController -> Table : this.table = table
activate Table
end box

box REST
Table -> EditTableController :
deactivate EditTableController
deactivate RemoteAppController

deactivate Table

EditTableController -> RemoteAppController : saveTable(table)
activate EditTableController
activate RemoteAppController
RemoteAppController -> Table : setTable(table)
activate RemoteAppController
activate Table
Table -> RemoteAppController :
deactivate Table
deactivate RemoteAppController

RemoteAppController -> RemoteAppController : saveTable()
activate RemoteAppController

RemoteAppController -> TableService : emptyTable()
activate TableService
TableService -> RemoteAppController
' PÅ LINJEN OVER KAN VI HA DOTTER DERSOM EMPTYTABLE() METODEN I REMOTEAPPCONTROLLER SENDER NOE TILBAKE TIL RAK ETTER Å HA SENDT REQUEST TIL REST
deactivate TableService

RemoteAppController -> TableService : HTTP PUT /sportstable/
activate TableService

TableService -> Table : addTeams(team)
activate TableService
activate Table
Table -> Table : sortTable()
Table -> TableService
deactivate Table
end box
deactivate TableService
TableService -> tablePersistence : autoSaveTable()
activate TableService


activate tablePersistence
tablePersistence -> tablePersistence : saveTable()

tablePersistence -> TableService
deactivate tablePersistence
deactivate TableService
TableService --> RemoteAppController: HTTP  true
deactivate TableService
deactivate RemoteAppController

RemoteAppController -> EditTableController
deactivate RemoteAppController
deactivate EditTableController
EditTableController -> GUI : stage.close()


deactivate EditTableControll
deactivate EditTableController
deactivate EditTableController

deactivate EditTableController

GUI -> you :




deactivate TableService

deactivate RemoteAppController
deactivate RemoteAppController






@enduml